### ISSUE TITLE
Not compatible with jupyter-client >= 7.0.0

### ISSUE THREAD

**Issue by phlummox** [mpastell/Pweave#165]
This issue arises using the current version of Pweave (Pweave-0.30.3) and Python 3.6.9 on Ubuntu 18.04.6.

## To reproduce:

```
$ python3.6 -m venv env && . ./env/bin/activate
$ echo > test.pmd
$ pweave --format=markdown test.pmd
```

## Expected output

```
$ pweave --format=markdown test.pmd
status
Weaved test.pmd to test.md
$ cat -n test.md
     1	
```

## Actual output

<details>
<summary>output follows:</summary>

```
status
Traceback (most recent call last):
  File "/home/user/test/env/bin/pweave", line 11, in <module>
    sys.exit(weave())
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/scripts.py", line 53, in weave
    pweave.weave(infile, **opts_dict)
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/__init__.py", line 59, in weave
    doc.weave()
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/pweb.py", line 192, in weave
    self.run()
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/pweb.py", line 127, in run
    self.wd
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/processors/jupyter.py", line 171, in __init__
    self.init_matplotlib()
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/processors/jupyter.py", line 174, in init_matplotlib
    self.loadstring(subsnippets.init_matplotlib)
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/processors/jupyter.py", line 134, in loadstring
    return self.run_cell(code_str)
  File "/home/user/test/env/lib/python3.6/site-packages/pweave/processors/jupyter.py", line 66, in run_cell
    msg = self.kc.get_shell_msg(timeout=timeout)
AttributeError: 'BlockingInProcessKernelClient' object has no attribute 'get_shell_msg'
```

</details>

## Comments

Versions of jupyter-client from 6.1.5 through to 6.1.12 inclusive seem to work fine. (This can be tested by running e.g. `pip install --upgrade Pweave 'jupyter-client==6.1.12'`.)

Earlier than 6.1.0, I assume one runs into issue https://github.com/mpastell/Pweave/issues/151.

**Comment by dequadras** [comment]
I have the same issue on mac, haven't yet been able to figure out which jupyter client to install

**Comment by phlummox** [comment]
Well, as I mention in the original issue, versions from 6.1.5 through to 6.1.12 seem to work fine.

But if you can't use those, then I think you may simply be out of luck. Pweave as it stands appears to be incompatible with recent versions of jupyter-client, and activity on the project seems to have ceased (the last activity by maintainers was in 2019).

**Comment by dequadras** [comment]
You are right, I changed to the version you mention and now it works, thanks!

**Comment by amichuda** [comment]
In case either of you are interested, a lot of the nice properties from `pweave` can now be found in `quarto`, which uses python natively and has support for a lot of nice format (and uses pandoc too).

https://quarto.org/

**Comment by phlummox** [comment]
> In case either of you are interested, a lot of the nice properties from `pweave` can now be found in `quarto`, which uses python natively and has support for a lot of nice format (and uses pandoc too).
> 
> https://quarto.org/

Ah, cool! I'll take a look. I actually ended up implementing my own mini- generator and templating engine to replace my use of Pweave, because Pweave contains a *lot* of features I just never use. But something better maintained than my own hacked together solution would be great. :)

**Comment by phlummox** [comment]
An update, for anyone coming across this issue: Pweave seems to be dead [\[1\]](https://github.com/psf/black/issues/3036#issuecomment-1108639024) [\[2\]](https://github.com/mpastell/Pweave/issues/161), but I listed some alternatives here:

* https://github.com/mpastell/Pweave/issues/161#issuecomment-1482606586
