### ISSUE TITLE
Testing fails when building the module for Debian Stretch

### ISSUE THREAD

**Issue by ghisvail** [mpastell/Pweave#58]
I am using the latest stable version on PyPI (version 0.25) with the packaged dependencies in Debian Stretch. The package fails to run the tests with the following output:

```
cd /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build; python3.5 -m nose tests
.............Warning, only the first figure gets a caption
Warning, only the first figure gets a caption
Warning, only the first figure gets a caption
Warning, only the first figure gets a caption
..S............./usr/lib/python3/dist-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
..DOCUMENTATION MODE ERROR:
Can't find stored results, running the code and caching results for the next documentation mode run
..FFFF.
======================================================================
FAIL: Test external python shell
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/tests/test_shell.py", line 19, in test_external_shell
    assertSameContent("tests/processors/processor_test.txt", "tests/processors/processor_external_ref.md")
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/tests/test_shell.py", line 30, in assertSameContent
    assert (out.read() == ref.read())
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Processing chunk 1 named None from line 5
Processing chunk 2 named None from line 12
Processing chunk 3 named None from line 16
Processing chunk 4 named None from line 20
Processing chunk 5 named None from line 24
Processing chunk 6 named None from line 29
Processing chunk 7 named None from line 33
Processing chunk 8 named None from line 37
Processing chunk 9 named None from line 41
Processing chunk 10 named None from line 46
Processing chunk 11 named None from line 50
Pweaved tests/processors/processor_test.mdw to tests/processors/processor_test.txt

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Test ipython python shell
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/tests/test_shell.py", line 24, in test_ipython_shell
    assertSameContent("tests/processors/ipy_processor_test.txt", "tests/processors/ipy_processor_ref.md")
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/tests/test_shell.py", line 30, in assertSameContent
    assert (out.read() == ref.read())
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Processing chunk 1 named None from line 5
Processing chunk 2 named None from line 9
Processing chunk 3 named None from line 13
Processing chunk 4 named None from line 17
Processing chunk 5 named None from line 21
Processing chunk 6 named None from line 26
Processing chunk 7 named None from line 30
Processing chunk 8 named None from line 34
Processing chunk 9 named None from line 38
Processing chunk 10 named None from line 43
Processing chunk 11 named None from line 47
Pweaved tests/processors/ipy_processor_test.mdw to tests/processors/ipy_processor_test.txt

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Test pypublish
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/tests/test_shell.py", line 38, in test_publish
    assert (test[:len(test) - 400] == ref[:len(test) - 400])
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Processing chunk 1 named None from line 7
Processing chunk 2 named None from line 59
Processing chunk 3 named None from line 66
Published tests/publish/publish_test.txt to tests/publish/publish_test.html

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Test pypublish cell format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/tests/test_shell.py", line 46, in test_publish_cell
    assert (test[:len(test) - 400] == ref[:len(test) - 400])
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Processing chunk 1 named None from line 7
Processing chunk 2 named None from line 59
Processing chunk 3 named None from line 66
Published tests/publish/publish_test_cell.txt to tests/publish/publish_test_cell.html

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
MARKDOWN: DEBUG: Successfully loaded extension "pweave.markdownmath.MathExtension".
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 38 tests in 23.741s

FAILED (SKIP=1, failures=4)
```
Any idea what is happening here?

**Comment by mpastell** [comment]
It could be just an issue with some of the depencies having a different version that was used to produce the reference output. You can compare the output to the reference to see what went wrong.
