### ISSUE TITLE
ptangle script fails in version 0.30

### ISSUE THREAD

**Issue by Joedang** [mpastell/Pweave#79]
I've tried this with TeX and Markdown source files on version 0.30. I'm not sure what's causing this, since I haven't gone mucking around in the `pweave` scripts. This occurs with the document I was actually working on, the example below, and even an empty file. 

Source file (`example.pmd`):

    Here is some text.
    
    ```python
    print('Here is some code!')
    ```

Traceback:
```
$ ptangle example.pmd
Traceback (most recent call last):
  File "/usr/local/bin/ptangle", line 11, in <module>
    sys.exit(tangle())
  File "/usr/local/lib/python3.4/dist-packages/pweave/scripts.py", line 97, in tangle
    pweave.tangle(infile, options.informat)
  File "/usr/local/lib/python3.4/dist-packages/pweave/__init__.py", line 66, in tangle
    doc = Pweb(file, kernel = None, informat = informat)
  File "/usr/local/lib/python3.4/dist-packages/pweave/pweb.py", line 69, in __init__
    self.setformat(doctype)
  File "/usr/local/lib/python3.4/dist-packages/pweave/pweb.py", line 150, in setformat
    kernel = self.kernel,
AttributeError: 'Pweb' object has no attribute 'kernel'

```

**Comment by mpastell** [comment]
Thanks, I have fixed this now. Sorry about it making to the release, I need to add a test for it.

**Comment by mpastell** [comment]
I pushed release 0.30.1 with this and another bug fix.
