### ISSUE TITLE
Probel with the kernel option for python2 

### ISSUE THREAD

**Issue by JamesLarkinWhite** [mpastell/Pweave#98]
IF i try to trun one of the test documents like:
pweave -f md2html --kernel python2 FIR_designp.pmd
or
pweave -f md2html -k python2 FIR_designp.pmd

I still get this error:

Traceback (most recent call last):
File "C:\Program Files (x86)\Python27\Lib\runpy.py", line 162, in run_module_as_main
"main", fname, loader, pkg_name)
File "C:\Program Files (x86)\Python27\Lib\runpy.py", line 72, in run_code
exec code in run_globals
File "C:\Program Files (x86)\Python27\Scripts\pweave.exe_main.py", line 5, in 
File "c:\program files (x86)\python27\lib\site-packages\pweave_init.py", line 6, in 
from . import readers
File "c:\program files (x86)\python27\lib\site-packages\pweave\readers.py", line 8, in 
from urllib import request, parse
ImportError: cannot import name request

I would really appreciate any help you are willing to offer.
At the moment i can not install python3 on this mashine

**Comment by mpastell** [comment]
You need to run Pweave using Python 3 even if you use Python 2 kernel. You can still use Pweave 0.25 with Python 2.

**Comment by JamesLarkinWhite** [comment]
Thank you very much for your support!!

IF i run: pweave -f md2html  FIR_designp.pmd

It starts to compile and i get and output document, but i also get the following error message i can not resolve. Would you be willing to give me a hint once more?

Processing chunk 1 named None from line 85
  Exception:
  DLL load failed: %1 ist keine zulõssige Win32-Anwendung.
  Error messages will be included in output document
  Exception:
  name 'signal' is not defined
  Error messages will be included in output document


Thank you in advance

**Comment by abukaj** [comment]
Seems to be problem with the code embedded in source of your document (in the first code chunk).
What error message is in the output of the document?
